SandVenturesCodingTest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^SandVentures/', include('primefinder.urls')),
]

primefinder/urls.py
from django.contrib.auth import authenticate
from django.conf.urls import patterns, include, url
from django.contrib import admin
import views

urlpatterns = patterns('',
    url(r'^findprime/$', views.PrimeNumberView.as_view(),name='prime-finder'),
    
)

primefinder/models.py
from django.db import models

# Create your models here.

primefinder/forms.py
from django.core.exceptions import ValidationError
from django import forms
from django.utils import html


def validate_number(value):
    try:
        int(value)
    except:
        raise ValidationError('%s is not a number!' % value)



        
class NumberForm(forms.Form):
    number= forms.CharField(label='Please Enter index number: ', max_length=20, validators=[validate_number])
    prime= forms.CharField(label='The prime number at this index is: ', max_length=20, required=False)

primefinder/views.py
from django.http import *
from django.views.generic import View
import json
from django.shortcuts import render
from forms import NumberForm
import logging, traceback
from backends import find_prime
logger = logging.getLogger(__name__)


# We use Class based view. Basically, the app is ajax based as finding a prime number may take some time. Hence I have integrated ajax post call with django. The core logic of finding nth prime number is put in a separate module, backend.py.
class PrimeNumberView(View):
    def get(self, request):
        template_name='prime_number_form.html'
        context={'prime_number':'Enter a Number!'}
        return render(request,template_name,context)

    def post(self,request):
        template_name = 'prime_number_form.html'
        post_dict=request.POST
        form_from_params=NumberForm(data=post_dict)
        if request.is_ajax():
            logger.info('Ajax request for finding the nth prime number has been received. ')
            if form_from_params.is_valid():        
                cleaned_data=form_from_params.cleaned_data
                number=int(cleaned_data['number'])
                results=find_prime(number)            
                returned_number=results[0]
                prime_number=results[1]# replace by the prime number and the returned index that we have found
                number=returned_number
                logger.info(prime_number)
                print returned_number, prime_number
            else:
                number=post_dict['number']            
                logger.error(form_from_params.errors.as_json()) 
                prime_number='Try Again, Number is invalid!'

            context={'number':number,'prime_number':prime_number}
            return HttpResponse(json.dumps(context), content_type='application/json')

primefinder/templates/prime_number_form.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
<script type='text/javascript' src='http://code.jquery.com/jquery-1.8.2.js'></script>
    <script type="text/javascript">

var click_handler= function (){
                    var input_string = $("#id_number").val();
                    $.ajax({
                        url : "/SandVentures/findprime/", 
                        type : "POST",
                        data : {
                            number : input_string,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                            },
                        success : function(json) {  
                            returned_number=json.number
                            if (returned_number == $('#id_number').val()){
                             
                             $('#id_prime').val(json.prime_number);            
                             }else{
                                $('#id_prime').val('Please wait, yet being calculated');
                                $('#id_number').val(input_string);
                                $('#button').click();
                                
                              }
                            
                        }
                        
                    });
                    return false;};

        $(document).ready(function() {$("#button").on('click', click_handler);});
</script>
 <form action="{% url 'prime-finder' %}" method=post name="primefinder"  id="forminput"  >    

      {% csrf_token %}
      <label for="id_number">number:</label>
      <input id="id_number" maxlength="20" name="number" value="{{number}}" type="text"/>
      <label for="id_prime">prime:</label>
      <input id="id_prime" maxlength="200" name="prime" value="{{prime_number}}" type="text"/>
      <div class="container"><input type="button" name="button" value="Lookup" id="button"/></div>

  </form>
</body>
</html>